package names

class CarolingianFrankishNames {
    fun generateName(isFemale: Boolean = false) = if (isFemale) femaleNames.random() else maleNames.random()

    private val femaleNames = setOf(
        "Audofleda",
        "Audovera",
        "Austrechild",
        "Beretrude",
        "Berthefled",
        "Berthegund",
        "Chlodosind",
        "Chlothsinda",
        "Clotild",
        "Faileuba",
        "Fredegunde",
        "Galswinth",
        "Goswinth",
        "Ingitrude",
        "Ingunde",
        "Lanthechilde",
        "Leubast",
        "Leubovera",
        "Magnatrude",
        "Marcatrude",
        "Marcovefa",
        "Radegund",
        "Rigunth",
        "Ultrogotha",
        "Vuldretrada"
    )

    private val maleNames = setOf(
        "Ageric",
        "Alaric",
        "Amalaric",
        "Andica",
        "Ansovald",
        "Arnegisel",
        "Athanaric",
        "Audovald",
        "Austregisel",
        "Authari",
        "Badegisel",
        "Berthar",
        "Bertram",
        "Bisinus",
        "Charibert",
        "Childebert",
        "Childeric",
        "Chlodomer",
        "Clovis",
        "Dagobert",
        "Eberulf",
        "Ebregisel",
        "Euric",
        "Garivald",
        "Godomar",
        "Gunderic",
        "Gunthar",
        "Guntram",
        "Hermangild",
        "Herminafrid",
        "Huneric",
        "Imnachar",
        "Ingomer",
        "Leudast",
        "Leuvigild",
        "Lothar",
        "Magneric",
        "Merovech",
        "Munderic",
        "Ragnarchar",
        "Rathar",
        "Reccared",
        "Sichar",
        "Sigeric",
        "Sigibert",
        "Sunnegisel",
        "Theudebald",
        "Theuderic",
        "Vulfoliac",
        "Willichar"
    )
}