package names

object EsquimauxNames {
    fun generateName(): String = names.random().first

    val names = setOf(
        Pair("Aguta", "Ag"),
        Pair("Akiak", "Ak"),
        Pair("Arjalinerk", "Arj"),
        Pair("Arrluk", "Arr"),
        Pair("Assiminik", "As"),
        Pair("Aukaneck", "Auk"),
        Pair("Chulyin", "Chul"),
        Pair("Cikuq", "Ci"),
        Pair("Iluq", "Il"),
        Pair("Issumatar", "Iss"),
        Pair("Kakortok", "Kak"),
        Pair("Karpok", "Kar"),
        Pair("Kesuk", "Ke"),
        Pair("Kinaktok", "Kin"),
        Pair("Kinapak", "Kin"),
        Pair("Krernertok", "Krer"),
        Pair("Kussuyok", "Kuss"),
        Pair("Maguyuk", "Mag"),
        Pair("Maniitok", "Man"),
        Pair("Nauja", "Nau"),
        Pair("Ningakpok", "Nin"),
        Pair("Nukilik", "Nuk"),
        Pair("Olipok", "Ol"),
        Pair("Piktaungitok", "Pik"),
        Pair("Pukulria", "Puk"),
        Pair("Qigiq", "Qig"),
        Pair("Saghani", "Sag"),
        Pair("Salaksartok", "Sal"),
        Pair("Sangilak", "San"),
        Pair("Saomik", "Sao"),
        Pair("Shila", "Shi"),
        Pair("Siku", "Si"),
        Pair("Sirmiq", "Sir"),
        Pair("Sitiyok", "Sit"),
        Pair("Sos", "Sos"),
        Pair("Suka", "Su"),
        Pair("Taliriktug", "Tal"),
        Pair("Taqukaq", "Taq"),
        Pair("Tartok", "Tar"),
        Pair("Tiglikte", "Tig"),
        Pair("Tikaani", "Tik"),
        Pair("Tonrar", "Ton"),
        Pair("Tornuaq", "Tor"),
        Pair("Tulugaq", "Tul"),
        Pair("Tulukaruk", "Tul"),
        Pair("Tungulria", "Tun"),
        Pair("Tuluwaq", "Tul"),
        Pair("Tuwawi", "Tuw"),
        Pair("Ulva", "Ul"),
        Pair("Yakone", "Yak")
    )
}