package names

class GreekNames {
    fun generateName(isFemale: Boolean = false): String = if (isFemale) {
        "${femaleNames.random()} ${maleNames.random()}"
    } else {
        "${maleNames.random()} ${maleNames.random()}"
    }

    private val femaleNames = setOf(
        "Agaue",
        "Airope",
        "Aithra",
        "Alkestis",
        "Alkippe",
        "Alkmene",
        "Amphithoe",
        "Amphitrite",
        "Antheia",
        "Antiochis",
        "Arete",
        "Artemidora",
        "Auge",
        "Charikleia",
        "Deianeira",
        "Diomede",
        "Dorothea",
        "Dynamene",
        "Eidothea",
        "Eunike",
        "Galatea",
        "Gorgo",
        "Halia",
        "Harmodios",
        "Iphimedeia",
        "Kalypso",
        "Kharmion",
        "Khryseis",
        "Khyrse",
        "Klymene",
        "Laodike",
        "Ligeia",
        "Marpessa",
        "Megaera",
        "Olympias",
        "Pasiphae",
        "Perialla",
        "Phaidra",
        "Pherenike",
        "Philomela",
        "Phyllis",
        "Polydamna",
        "Polyxena",
        "Rhoxane",
        "Sostrate",
        "Telephassa",
        "Xanthe",
        "Xanthippe",
        "Xene",
        "Zosime"
    )

    private val maleNames = setOf(
        "Agathokles",
        "Agenor",
        "Aietes",
        "Akrisios",
        "Antichares",
        "Antiochos",
        "Antisthenes",
        "Bion",
        "Chrestos",
        "Damoetas",
        "Daphnis",
        "Demoleon",
        "Epaphroditos",
        "Eudoxos",
        "Eugammon",
        "Eumastas",
        "Eumenes",
        "Euonomos",
        "Euthydemos",
        "Galenos",
        "Heron",
        "Hippasos",
        "Iason",
        "Isagoras",
        "Keitos",
        "Kleomenes",
        "Kynaegeiros",
        "Leukippos",
        "Lycophron",
        "Melas",
        "Menekrates",
        "Nikandros",
        "Onesimos",
        "Orsilochos",
        "Panetios",
        "Phalanthos",
        "Phegeus",
        "Philokles",
        "Philon",
        "Polyneikes",
        "Ptolemaios",
        "Sophokles",
        "Telamon",
        "Telesphoros",
        "Thales",
        "Theognis",
        "Thrasyboulos",
        "Tros",
        "Xenokrates",
        "Zotikos"
    )
}