package names

object VikingNames {

    private fun generateMaleName() {
        val father = maleNames.random()
    }

    private fun String.getFatherMod(): String {
        return nameMods
            .asSequence()
            .firstOrNull { endsWith(it.key) }
            ?.value
            ?: ""
    }


    private val femaleNames = setOf(
        "Alfhildr",
        "Arnbjorg",
        "Arndis",
        "Arnfridr",
        "Arngerdr",
        "Arngunnr",
        "Arnlaug",
        "Asbjorg",
        "Asfridr",
        "Asgerdr",
        "Asgunnr",
        "Asny",
        "Astridr",
        "Dis",
        "Eybjorg",
        "Eydis",
        "Freydis",
        "Freygerdr",
        "Freygunnr",
        "Frida",
        "Geira",
        "Geirbjorg",
        "Geirhildr",
        "Geirlaug",
        "Geirridr",
        "Gislaug",
        "Groa",
        "Gunna",
        "Gunnfridr",
        "Gunnheidr",
        "Gunnhildr",
        "Gunnlaug",
        "Gunnvor",
        "Gyda",
        "Halla",
        "Hallbera",
        "Hallbjorg",
        "Halldis",
        "Hallfridr",
        "Hallgerdr",
        "Hallthora",
        "Hallveig",
        "Heimlaug",
        "Helga",
        "Herdis",
        "Herfridr",
        "Hergerdr",
        "Hergunnr",
        "Herthrudr",
        "Hildibjorg",
        "Hildigerdr",
        "Hildigunnr",
        "Hildr",
        "Hlif",
        "Hlifhildr",
        "Holmfridr",
        "Holmgerdr",
        "Holmlaug",
        "Hrefna",
        "Inga",
        "Ingibjorg",
        "Ingigerdr",
        "Ingileif",
        "Ingiridr",
        "Jofridr",
        "Jorunn",
        "Ketillaug",
        "Ketilridr",
        "Maer",
        "Magnhildr",
        "Mundgerdr",
        "Oddbjorg",
        "Oddfridr",
        "Oddny",
        "Ragnbjorg",
        "Ragnfridr",
        "Ragnhildr",
        "Rannveig",
        "Sigbjorg",
        "Signy",
        "Sigridr",
        "Sigrun",
        "Sigthrudr",
        "Snaelaug",
        "Steinbjorg",
        "Steinfridr",
        "Thuridr",
        "Thyri",
        "Ulfhildr",
        "Ulla",
        "Ullgerdr",
        "Ullgunnr",
        "Ullhildr",
        "Ullunn",
        "Ullve",
        "Ullvor",
        "Unna",
        "Unnr",
        "Vefridr",
        "Vegerdr"
    )

    private val maleNames = setOf(
        "Aghi",
        "Alfarr",
        "Arnfastr",
        "Arngrimr",
        "Arnhallr",
        "Arnhvatr",
        "Arnkell",
        "Arnstienn",
        "Arnvidr",
        "Asbrandr",
        "Asgeirr",
        "Askell",
        "Asmarr",
        "Asulfr",
        "Audbjorn",
        "Audgrimr",
        "Audkell",
        "Audulfr",
        "Audstienn",
        "Audvidr",
        "Baggi",
        "Balli",
        "Bergr",
        "Bersi",
        "Bjartr",
        "Bjorn",
        "Bjornkell",
        "Brandr",
        "Brandulfr",
        "Broddr",
        "Brunkell",
        "Dagr",
        "Dagvidr",
        "Einarr",
        "Eirikr",
        "Eldgrimr",
        "Eybjorn",
        "Fastmundr",
        "Fastulfr",
        "Fjolmodr",
        "Frakki",
        "Freygeirr",
        "Freyrikr",
        "Freyvidr",
        "Frodi",
        "Gedda",
        "Geirfastr",
        "Geirleifr",
        "Geirmodr",
        "Geirr",
        "Grimkell",
        "Grimr",
        "Gunnr",
        "Gunnkell",
        "Gunnleifr",
        "Gunnvidr",
        "Hafr",
        "Haki",
        "Hakon",
        "Hallbjorn",
        "Hallgrimr",
        "Hallr",
        "Haukr",
        "Helgi",
        "Hermundr",
        "Holmfastr",
        "Holmkell",
        "Hrolfr",
        "Ingi",
        "Ivarr",
        "Jofurr",
        "ketill",
        "Knutr",
        "Lodinn",
        "Magnus",
        "Oddi",
        "Oleifr",
        "Orri",
        "Ragnarr",
        "Runi",
        "Sigmundr",
        "Sigtryggr",
        "Sigurdr",
        "Snaebjorn",
        "Snorri",
        "Solvi",
        "Steinn",
        "Stigr",
        "Sunnvidr",
        "Ulfr",
        "Ulbjorn",
        "Ullbrandr",
        "Ulldr",
        "Ullfredr",
        "Ullgeirr",
        "Ullgrimr",
        "Ullir",
        "Ullvaldr",
        "Vedr",
        "Vigmadr"
    )

    private val nameMods = mapOf(
        "bjorn" to "biarnar",
        "dr" to "ar",
        "i" to "a",
        "ir" to "a",
        "ll" to "ls",
        "nn" to "ns",
        "rr" to "rs",
        "r" to "s"
    )
}