package names

object VikingNames {

    fun generateName(isFemale: Boolean) = if (isFemale) generateFemaleName() else generateMaleName()

    private fun generateMaleName() = "${maleNames.random()} ${generateLastName(false)}"

    private fun generateFemaleName() = "${femaleNames.random()} ${generateLastName(true)}"

    private fun generateLastName(isFemale: Boolean) = maleNames
        .random()
        .let {
            val mod = it.getFatherMod()
            it.dropLast(mod.original.length) + mod.new + sonOrDaughter(isFemale)
        }

    private fun String.getFatherMod() = nameMods.firstOrNull {
        endsWith(it.original)
    } ?: NameMod(original = "", new = "")


    private val femaleNames = setOf(
        "Alfhildr",
        "Arnbjorg",
        "Arndis",
        "Arnfridr",
        "Arngerdr",
        "Arngunnr",
        "Arnlaug",
        "Asbjorg",
        "Asfridr",
        "Asgerdr",
        "Asgunnr",
        "Asny",
        "Astridr",
        "Dis",
        "Eybjorg",
        "Eydis",
        "Freydis",
        "Freygerdr",
        "Freygunnr",
        "Frida",
        "Geira",
        "Geirbjorg",
        "Geirhildr",
        "Geirlaug",
        "Geirridr",
        "Gislaug",
        "Groa",
        "Gunna",
        "Gunnfridr",
        "Gunnheidr",
        "Gunnhildr",
        "Gunnlaug",
        "Gunnvor",
        "Gyda",
        "Halla",
        "Hallbera",
        "Hallbjorg",
        "Halldis",
        "Hallfridr",
        "Hallgerdr",
        "Hallthora",
        "Hallveig",
        "Heimlaug",
        "Helga",
        "Herdis",
        "Herfridr",
        "Hergerdr",
        "Hergunnr",
        "Herthrudr",
        "Hildibjorg",
        "Hildigerdr",
        "Hildigunnr",
        "Hildr",
        "Hlif",
        "Hlifhildr",
        "Holmfridr",
        "Holmgerdr",
        "Holmlaug",
        "Hrefna",
        "Inga",
        "Ingibjorg",
        "Ingigerdr",
        "Ingileif",
        "Ingiridr",
        "Jofridr",
        "Jorunn",
        "Ketillaug",
        "Ketilridr",
        "Maer",
        "Magnhildr",
        "Mundgerdr",
        "Oddbjorg",
        "Oddfridr",
        "Oddny",
        "Ragnbjorg",
        "Ragnfridr",
        "Ragnhildr",
        "Rannveig",
        "Sigbjorg",
        "Signy",
        "Sigridr",
        "Sigrun",
        "Sigthrudr",
        "Snaelaug",
        "Steinbjorg",
        "Steinfridr",
        "Thuridr",
        "Thyri",
        "Ulfhildr",
        "Ulla",
        "Ullgerdr",
        "Ullgunnr",
        "Ullhildr",
        "Ullunn",
        "Ullve",
        "Ullvor",
        "Unna",
        "Unnr",
        "Vefridr",
        "Vegerdr"
    )

    private val maleNames = setOf(
        "Aghi",
        "Alfarr",
        "Arnfastr",
        "Arngrimr",
        "Arnhallr",
        "Arnhvatr",
        "Arnkell",
        "Arnstienn",
        "Arnvidr",
        "Asbrandr",
        "Asgeirr",
        "Askell",
        "Asmarr",
        "Asulfr",
        "Audbjorn",
        "Audgrimr",
        "Audkell",
        "Audulfr",
        "Audstienn",
        "Audvidr",
        "Baggi",
        "Balli",
        "Bergr",
        "Bersi",
        "Bjartr",
        "Bjorn",
        "Bjornkell",
        "Brandr",
        "Brandulfr",
        "Broddr",
        "Brunkell",
        "Dagr",
        "Dagvidr",
        "Einarr",
        "Eirikr",
        "Eldgrimr",
        "Eybjorn",
        "Fastmundr",
        "Fastulfr",
        "Fjolmodr",
        "Frakki",
        "Freygeirr",
        "Freyrikr",
        "Freyvidr",
        "Frodi",
        "Gedda",
        "Geirfastr",
        "Geirleifr",
        "Geirmodr",
        "Geirr",
        "Grimkell",
        "Grimr",
        "Gunnr",
        "Gunnkell",
        "Gunnleifr",
        "Gunnvidr",
        "Hafr",
        "Haki",
        "Hakon",
        "Hallbjorn",
        "Hallgrimr",
        "Hallr",
        "Haukr",
        "Helgi",
        "Hermundr",
        "Holmfastr",
        "Holmkell",
        "Hrolfr",
        "Ingi",
        "Ivarr",
        "Jofurr",
        "ketill",
        "Knutr",
        "Lodinn",
        "Magnus",
        "Oddi",
        "Oleifr",
        "Orri",
        "Ragnarr",
        "Runi",
        "Sigmundr",
        "Sigtryggr",
        "Sigurdr",
        "Snaebjorn",
        "Snorri",
        "Solvi",
        "Steinn",
        "Stigr",
        "Sunnvidr",
        "Ulfr",
        "Ulbjorn",
        "Ullbrandr",
        "Ulldr",
        "Ullfredr",
        "Ullgeirr",
        "Ullgrimr",
        "Ullir",
        "Ullvaldr",
        "Vedr",
        "Vigmadr"
    )

    private val nameMods = setOf(
        NameMod("bjorn", "biarnar"),
        NameMod("dr", "ar"),
        NameMod("i", "a"),
        NameMod("ir", "a"),
        NameMod("ll", "ls"),
        NameMod("nn", "ns"),
        NameMod("rr", "rs"),
        NameMod("r", "s")
    )


    private fun sonOrDaughter(isFemale: Boolean) = if (isFemale) "dottir" else "son"

}

data class NameMod(val original: String, val new: String)

